use_frameworks!

target 'SwiftyComponent_Example' do
  pod 'SwiftyComponent', :path => '../'

  target 'SwiftyComponent_Tests' do
    inherit! :search_paths
  end
  
  # Workaround for Cocoapods issue #7606
    post_install do |installer|
        installer.pods_project.build_configurations.each do |config|
            next unless config.name == 'Debug'
            config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = [
              '$(FRAMEWORK_SEARCH_PATHS)'
            ]
        end
    end
end
